### ISSUE TITLE
Access denied when copying from s3

### ISSUE THREAD

**Issue by evaldsurtans** [MaAleBarr/voices18.github.io#1]
After about few minutes I get "Access denied" errors for copying dataset. In beginning, all files can be coppied.

What is the transaction limit per second for this dataset? Maybe I am downloading it too fast?
Or is there some other reason?

![image](https://user-images.githubusercontent.com/1777062/42474656-f293374a-83d0-11e8-95bb-8c78ff3247b6.png)

**Comment by evaldsurtans** [comment]
I tested this also on ec2 instance and I confirm that more than a half of data is inaccessible in bucket

**Comment by MaAleBarr** [comment]
@evaldsurtans we have changed the structure of the data, all are now .tar.gz files and have made corrections to permissions. Take a look now. Thanks for reporting.
